/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Hotel_Reservation_System;

/**
 *
 * @author imash
 */
public class FormIncomeReport extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormIncomeReport.class.getName());

  public void loadIncomeReport() {
    
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblReport.getModel();
        model.setRowCount(0); 
        
        double grandTotalIncome = 0.0;
        
        String sql = "SELECT b.booking_id, b.guest_id, b.room_no, b.total_days, b.check_in_date, r.room_type " +
                     "FROM bookings b " +
                     "INNER JOIN rooms r ON b.room_no = r.room_no";

        try (java.sql.Connection conn = DB_Connection.connect();
             java.sql.PreparedStatement pst = conn.prepareStatement(sql);
             java.sql.ResultSet rs = pst.executeQuery()) {

            boolean hasData = false;
            int paymentCounter = 1; 

            while (rs.next()) {
                hasData = true;
                int bookingId = rs.getInt("booking_id");
                int guestId = rs.getInt("guest_id");
                String roomNo = rs.getString("room_no");
                int totalDays = rs.getInt("total_days");
                java.sql.Date date = rs.getDate("check_in_date");
                String roomType = rs.getString("room_type");

                int days = (totalDays <= 0) ? 1 : totalDays;
                
                double pricePerNight = 5000.0; // Default Single
                if (roomType.equalsIgnoreCase("Double")) {
                    pricePerNight = 8500.0;
                } else if (roomType.equalsIgnoreCase("Luxury")) {
                    pricePerNight = 15000.0;
                }
                
                double amount = days * pricePerNight; 
                grandTotalIncome += amount;

                model.addRow(new Object[]{
                     "P" + String.format("%03d", paymentCounter++), 
                     "G" + String.format("%03d", guestId),          
                     "B" + String.format("%03d", bookingId),        
                     "Rs. " + String.format("%.2f", amount),        
                     "Cash/Card",                                    
                     date != null ? date.toString() : "N/A"         
                });
            }

            lblTotalIncome.setText("Total Hotel Income: Rs. " + String.format("%.2f", grandTotalIncome));

            if (hasData) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "📊 Total Hotel Income: Rs. " + String.format("%.2f", grandTotalIncome), 
                    "Income Report", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "There are no records in the bookings table!", 
                    "Information", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Database connection error", ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    

}
    public FormIncomeReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Payment ID", "Guest ID", "Booking ID", "Amount", "Payment Method", "Date"}
        ));
        loadIncomeReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        lblTotalIncome = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hotel Financial Income Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        tblReport.setBackground(new java.awt.Color(204, 255, 204));
        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Guest ID", "Booking ID", "Amount", "Payment Method", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 706, 280));

        lblTotalIncome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalIncome.setText("Total Hotel Income: Rs. 0.00");
        getContentPane().add(lblTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 385, 270, -1));

        btnClose.setBackground(new java.awt.Color(153, 153, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormIncomeReport dialog = new FormIncomeReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalIncome;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
