/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_Reservation_System;

/**
 *
 * @author imash
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    private String currentUserRole = "Staff";
    
    public MainDashboard(String userRole) {
        this.currentUserRole = userRole;
        initComponents();
       
      
        this.setLocationRelativeTo(null);
        
        if (!"Manager".equalsIgnoreCase(currentUserRole)) {
            btnStaffLogin.setVisible(false); 
        }
        
        pnlContent.remove(pnlSidebar); 
        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST); 
        
        javax.swing.JPanel pnlEmpty = new javax.swing.JPanel();
        pnlEmpty.setBackground(pnlContent.getBackground()); 
        pnlContent.add(pnlEmpty, "cardEmpty");
        
        pnlContent.add(new PanelStaffMenu(), "cardStaffMenu"); 
    
    pnlContent.add(new PanelUsers(), "cardStaffLogin");
    pnlContent.add(new PanelRooms(), "cardRooms");
    pnlContent.add(new PanelGuests(), "cardCustomers");
    pnlContent.add(new PanelBookings(), "cardBookings");
    
    java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
    layout.show(pnlContent, "cardEmpty");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        btnStaffLogin = new javax.swing.JButton();
        btnCustomerRegister = new javax.swing.JButton();
        btnBookingRooms = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContent.setBackground(new java.awt.Color(204, 204, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlSidebar.setBackground(new java.awt.Color(0, 51, 204));
        pnlSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStaffLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnStaffLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStaffLogin.setText("Staff Login");
        btnStaffLogin.addActionListener(this::btnStaffLoginActionPerformed);
        pnlSidebar.add(btnStaffLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 111, 32));

        btnCustomerRegister.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomerRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCustomerRegister.setText("Customer Register");
        btnCustomerRegister.addActionListener(this::btnCustomerRegisterActionPerformed);
        pnlSidebar.add(btnCustomerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, 32));

        btnBookingRooms.setBackground(new java.awt.Color(204, 204, 255));
        btnBookingRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBookingRooms.setText("Booking rooms");
        btnBookingRooms.addActionListener(this::btnBookingRoomsActionPerformed);
        pnlSidebar.add(btnBookingRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 134, 35));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Ceylon Paradise");
        pnlSidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 500, 113));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Hotel");
        pnlSidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 199, 57));

        pnlContent.add(pnlSidebar, "card3");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
    
    
    layout.show(pnlContent, "cardStaffLogin");
    }//GEN-LAST:event_btnStaffLoginActionPerformed

    private void btnCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerRegisterActionPerformed
   ((java.awt.CardLayout) pnlContent.getLayout()).show(pnlContent, "cardCustomers");
    }//GEN-LAST:event_btnCustomerRegisterActionPerformed

    private void btnBookingRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingRoomsActionPerformed
    showPanel("cardBookings");
    }//GEN-LAST:event_btnBookingRoomsActionPerformed
public void showPanel(String cardName) {
    if (pnlContent != null && pnlContent.getLayout() instanceof java.awt.CardLayout) {
        ((java.awt.CardLayout) pnlContent.getLayout()).show(pnlContent, cardName);
    }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard("Manager").setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingRooms;
    private javax.swing.JButton btnCustomerRegister;
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables
}
