/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel_Reservation_System;

/**
 *
 * @author imash
 */
public class PanelStaffMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelStaffMenu
     */
    public PanelStaffMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoToRooms = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBackToLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoToRooms.setBackground(new java.awt.Color(102, 102, 255));
        btnGoToRooms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGoToRooms.setText("Go to Room Update");
        btnGoToRooms.addActionListener(this::btnGoToRoomsActionPerformed);
        add(btnGoToRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnViewReport.setBackground(new java.awt.Color(102, 102, 255));
        btnViewReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewReport.setText("View Income Report");
        btnViewReport.addActionListener(this::btnViewReportActionPerformed);
        add(btnViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 109, -1));

        btnBackToLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnBackToLogin.setText("◀ Back");
        btnBackToLogin.addActionListener(this::btnBackToLoginActionPerformed);
        add(btnBackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 82, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
     
   
    FormIncomeReport report = new FormIncomeReport((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true);
    report.setLocationRelativeTo(this);
    
    
    report.setVisible(true);  
    
   



    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnGoToRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToRoomsActionPerformed
                                                
    java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    if (ancestor instanceof MainDashboard) {
        MainDashboard dashboard = (MainDashboard) ancestor;
        dashboard.showPanel("cardRooms"); 
    }




  

    }//GEN-LAST:event_btnGoToRoomsActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed

    java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    if (ancestor instanceof MainDashboard) {
        MainDashboard dashboard = (MainDashboard) ancestor;
        
        dashboard.showPanel("cardStaffLogin"); 
        
    } else {
  
        java.awt.Container parent = this.getParent();
        if (parent != null && parent.getLayout() instanceof java.awt.CardLayout) {
            ((java.awt.CardLayout) parent.getLayout()).show(parent, "cardStaffLogin");
        }
    }


    }//GEN-LAST:event_btnBackToLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnGoToRooms;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
