/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel_Reservation_System;

/**
 *
 * @author imash
 */
public class PanelBookings extends javax.swing.JPanel {

    /**
     * Creates new form PanelBookings
     */
    public PanelBookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGuestID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Room Booking System");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Guest ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 79, -1, -1));
        add(txtGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 76, 496, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Full Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 113, 116, -1));
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 110, 496, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NIC Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 147, -1, -1));

        txtNIC.addActionListener(this::txtNICActionPerformed);
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 144, 209, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Contact No:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 187, 90, -1));

        txtContactNo.addActionListener(this::txtContactNoActionPerformed);
        add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 184, 209, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 221, 105, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 218, 496, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 258, 87, -1));

        txtAddress.addActionListener(this::txtAddressActionPerformed);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 258, 496, -1));

        btnNext.setBackground(new java.awt.Color(102, 153, 255));
        btnNext.setText("Next ➡️");
        btnNext.addActionListener(this::btnNextActionPerformed);
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 413, 110, 40));
        add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 292, 496, -1));
        add(txtAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 326, 496, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
 String guestIdStr = txtGuestID.getText().trim();
        String fullName = txtFullName.getText().trim();
        String nic = txtNIC.getText().trim();
        String contactNo = txtContactNo.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();

        if (guestIdStr.isEmpty() || fullName.isEmpty() || nic.isEmpty() || contactNo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all required Guest details!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO guests (guest_id, full_name, nic_or_passport, contact_number, email_address, address) VALUES (?, ?, ?, ?, ?, ?)";

       
int guestId = 0; 

try {
    
    if (guestIdStr.toUpperCase().startsWith("G")) {
        guestId = Integer.parseInt(guestIdStr.substring(1));
    } else {
        guestId = Integer.parseInt(guestIdStr);
    }
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Guest ID must be a valid number!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try (java.sql.Connection conn = DB_Connection.connect();
     java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
    
    pst.setInt(1, guestId);
    pst.setString(2, fullName);
    pst.setString(3, nic);
    pst.setString(4, contactNo);
    pst.setString(5, email);
    pst.setString(6, address);
    
    pst.executeUpdate(); 
    
    java.awt.Container parent = this.getParent();
    while (parent != null && !(parent instanceof javax.swing.JFrame)) {
        parent = parent.getParent();
    }
    
    if (parent != null) {
        javax.swing.JFrame mainFrame = (javax.swing.JFrame) parent;
        PanelRoomSelection roomPanel = new PanelRoomSelection(guestId, fullName);
    
        mainFrame.getContentPane().removeAll();
        mainFrame.getContentPane().add(roomPanel);
        mainFrame.revalidate();
        mainFrame.repaint();
        
        txtGuestID.setText(""); txtFullName.setText(""); txtNIC.setText("");
        txtContactNo.setText(""); txtEmail.setText(""); txtAddress.setText("");
    }
    
} catch (java.sql.SQLIntegrityConstraintViolationException ex) {
  
    java.awt.Container parent = this.getParent();
    while (parent != null && !(parent instanceof javax.swing.JFrame)) {
        parent = parent.getParent();
    }
    
    if (parent != null) {
        javax.swing.JFrame mainFrame = (javax.swing.JFrame) parent;
        PanelRoomSelection roomPanel = new PanelRoomSelection(guestId, fullName);
    
        mainFrame.getContentPane().removeAll();
        mainFrame.getContentPane().add(roomPanel);
        mainFrame.revalidate();
        mainFrame.repaint();
        
        txtGuestID.setText(""); txtFullName.setText(""); txtNIC.setText("");
        txtContactNo.setText(""); txtEmail.setText(""); txtAddress.setText("");
    }
} catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGuestID;
    private javax.swing.JTextField txtNIC;
    // End of variables declaration//GEN-END:variables
}
