/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel_Reservation_System;

public class PanelPayment extends javax.swing.JPanel {

private int guestId;
private String roomNo;
private String checkIn;
private String checkOut;
private int adults;
private int children;
private int totalDays;
private double totalAmount;
private javax.swing.JPanel mainPanel; 

   
    public PanelPayment() {
        initComponents();
    }

    
    public PanelPayment(int guestId, String roomNo, String checkIn, String checkOut, int adults, int children, int totalDays, double totalAmount, javax.swing.JPanel mainPanel) {
    initComponents();
    this.guestId = guestId;
    this.roomNo = roomNo;
    this.checkIn = checkIn;
    this.checkOut = checkOut;
    this.adults = adults;
    this.children = children;
    this.totalDays = totalDays;
    this.totalAmount = totalAmount;
    this.mainPanel = mainPanel;
        
       txtGuestID.setText(String.format("G%03d", guestId)); 
       txtAmount.setText("Rs. " + String.format("%.2f", totalAmount)); 
       txtPayAmount.setText(String.format("%.2f", totalAmount));
       cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Online Transfer" }));
        
    lblCardNo.setVisible(false); 
    txtCardNumber.setVisible(false);
    lblPayAmount.setVisible(false); 
    txtPayAmount.setVisible(false); 
     
    cmbPaymentMethod.addActionListener(e -> {
        String selectedMethod = cmbPaymentMethod.getSelectedItem().toString();
        boolean isCard = selectedMethod.equals("Card");
        
        lblCardNo.setVisible(isCard);
        txtCardNumber.setVisible(isCard);
        lblPayAmount.setVisible(isCard);
        txtPayAmount.setVisible(isCard);
        
        this.revalidate();
        this.repaint();
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGuestID = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        btnPay = new javax.swing.JButton();
        lblCardNo = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        lblPayAmount = new javax.swing.JLabel();
        txtPayAmount = new javax.swing.JTextField();
        btnBackToRoomSelect = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Guest ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Total Amount");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Payment Method");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 142, -1, -1));
        add(txtGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 65, 139, -1));
        add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 99, 139, -1));

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card ", "Cash" }));
        add(cmbPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 139, -1, -1));

        btnPay.setBackground(new java.awt.Color(102, 153, 255));
        btnPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPay.setText("Pay Now");
        btnPay.addActionListener(this::btnPayActionPerformed);
        add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 256, 100, -1));

        lblCardNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCardNo.setText("Card Number");
        add(lblCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 176, -1, -1));
        add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 173, 139, -1));

        lblPayAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPayAmount.setText("Amount to Pay");
        add(lblPayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 213, -1, -1));
        add(txtPayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 213, 139, -1));

        btnBackToRoomSelect.setBackground(new java.awt.Color(153, 153, 153));
        btnBackToRoomSelect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBackToRoomSelect.setText("← Back");
        btnBackToRoomSelect.addActionListener(this::btnBackToRoomSelectActionPerformed);
        add(btnBackToRoomSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
                                     
    String updateRoomSql = "UPDATE rooms SET status = 'Booked' WHERE room_no = ?";
    String insertBookingSql = "INSERT INTO bookings (guest_id, room_no, check_in_date, check_out_date, adults, children, total_days) VALUES (?, ?, ?, ?, ?, ?, ?)";
    
    int generatedBookingId = 0;

    try (java.sql.Connection conn = DB_Connection.connect()) {
        conn.setAutoCommit(false); 

        try (java.sql.PreparedStatement pst1 = conn.prepareStatement(updateRoomSql);
             java.sql.PreparedStatement pst2 = conn.prepareStatement(insertBookingSql, java.sql.Statement.RETURN_GENERATED_KEYS)) {
           
            pst1.setString(1, this.roomNo);
            pst1.executeUpdate();

            pst2.setInt(1, this.guestId);
            pst2.setString(2, this.roomNo);
            pst2.setString(3, this.checkIn);
            pst2.setString(4, this.checkOut);
            pst2.setInt(5, this.adults);
            pst2.setInt(6, this.children);
            pst2.setInt(7, this.totalDays);
            pst2.executeUpdate();
           
            try (java.sql.ResultSet generatedKeys = pst2.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    generatedBookingId = generatedKeys.getInt(1);
                }
            }

            conn.commit(); 
            
            String formattedBookingId = String.format("B%03d", generatedBookingId);
            String formattedGuestId = String.format("G%03d", this.guestId);

            
                    String message = "🎉 Payment Successful & Room Booked!\n\n"
                    + "🔹 Guest ID          : " + formattedGuestId + "\n"
                    + "🔹 Booking ID      : " + formattedBookingId + "\n"
                    + "🔹 Room No         : " + this.roomNo + "\n"
                    + "🔹 Amount Paid  : Rs. " + String.format("%.2f", this.totalAmount);

            javax.swing.JOptionPane.showMessageDialog(this, message, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (mainPanel != null) {
                mainPanel.removeAll();
                PanelRoomSelection roomSelection = new PanelRoomSelection(this.guestId, "");
                mainPanel.add(roomSelection);
                mainPanel.revalidate();
                mainPanel.repaint();
            }

        } catch (Exception ex) {
            conn.rollback(); 
            throw ex;
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Transaction Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnBackToRoomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToRoomSelectActionPerformed
   
    java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    if (ancestor instanceof MainDashboard) {
        MainDashboard dashboard = (MainDashboard) ancestor;
       
        dashboard.showPanel("cardRoomSelection");
        
    } else {
        
        java.awt.Container parent = this.getParent();
        if (parent != null && parent.getLayout() instanceof java.awt.CardLayout) {
            ((java.awt.CardLayout) parent.getLayout()).show(parent, "cardRoomSelection");
        }
    }

    }//GEN-LAST:event_btnBackToRoomSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToRoomSelect;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCardNo;
    private javax.swing.JLabel lblPayAmount;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtGuestID;
    private javax.swing.JTextField txtPayAmount;
    // End of variables declaration//GEN-END:variables
}
