/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel_Reservation_System;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class PanelRooms extends javax.swing.JPanel {

    /**
     * Creates new form PanelRooms
     */
    public PanelRooms() {
        initComponents();
        loadRoomData();
    }
    
    public void loadRoomData() {
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0); 
        
        model.setColumnIdentifiers(new String[]{"Room No", "Room Type", "Price", "Status", "Amenities"});

        try {
            Connection con = DB_Connection.connect(); 
            String query = "SELECT * FROM rooms";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                int roomNo = rs.getInt("room_no");
                String type = rs.getString("room_type");
                double price = rs.getDouble("price_per_night");
                String status = rs.getString("status");
                String amenities = rs.getString("amenities");

                model.addRow(new Object[]{roomNo, type, price, status, amenities});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbRoomType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbAmenities = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancelBooking = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("Room Management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Room Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Room Type");

        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Luxury " }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Status");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amenities");

        cmbAmenities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed, Fan, Attached Bathroom, Free Wi-Fi", "Double Bed, AC, Attached Bathroom, Smart TV, Free Wi-Fi", "King Size Bed, AC, Mini Fridge, Bathtub, Smart TV, Pool Access" }));

        btnUpdate.setBackground(new java.awt.Color(102, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update Room");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        tblRooms.setBackground(new java.awt.Color(204, 255, 204));
        tblRooms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Price", "Status", "Amentities"
            }
        ));
        tblRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        btnAdd.setBackground(new java.awt.Color(102, 153, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add Room");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnClear.setBackground(new java.awt.Color(102, 153, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("◀ Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnCancelBooking.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelBooking.setText("Release Room");
        btnCancelBooking.addActionListener(this::btnCancelBookingActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelBooking)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdate)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAdd)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(btnClear))))))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomsMouseClicked
       int selectedRow = tblRooms.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
    
   
    txtRoomNo.setText(model.getValueAt(selectedRow, 0).toString());
    cmbRoomType.setSelectedItem(model.getValueAt(selectedRow, 1).toString());
    txtPrice.setText(model.getValueAt(selectedRow, 2).toString());
    cmbStatus.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
    cmbAmenities.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tblRoomsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
  try {
        Connection con = DB_Connection.connect();
        String query = "UPDATE rooms SET room_type=?, price_per_night=?, status=?, amenities=? WHERE room_no=?";
        
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, cmbRoomType.getSelectedItem().toString());
        pst.setDouble(2, Double.parseDouble(txtPrice.getText()));
        pst.setString(3, cmbStatus.getSelectedItem().toString());
       pst.setString(4, cmbAmenities.getSelectedItem().toString());
        pst.setInt(5, Integer.parseInt(txtRoomNo.getText())); // WHERE room_no = ?
        
        int result = pst.executeUpdate();
        if(result > 0) {
            JOptionPane.showMessageDialog(this, "Room Updated Successfully!");
            loadRoomData(); // Table එක අලුත් දත්ත වලින් Refresh කිරීම
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update Failed: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
  if (txtRoomNo.getText().trim().isEmpty() || txtPrice.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields (Room No and Price)!");
        return;
    }

    try {
        Connection con = DB_Connection.connect();
        
        String query = "INSERT INTO rooms (room_no, room_type, price_per_night, status, amenities) VALUES (?, ?, ?, ?, ?)";
        
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, Integer.parseInt(txtRoomNo.getText()));
        pst.setString(2, cmbRoomType.getSelectedItem().toString());
        pst.setDouble(3, Double.parseDouble(txtPrice.getText()));
        pst.setString(4, cmbStatus.getSelectedItem().toString());
        pst.setString(5, cmbAmenities.getSelectedItem().toString());
        
        int result = pst.executeUpdate();
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "New Room Added Successfully!");
            loadRoomData(); 
        }
    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        
        JOptionPane.showMessageDialog(this, "This Room Number already exists!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Insertion Failed: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed
private void clearFields() {
        txtRoomNo.setText("");
        cmbRoomType.setSelectedIndex(0);
        txtPrice.setText("");
        cmbStatus.setSelectedIndex(0);
        cmbAmenities.setSelectedIndex(0);
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
 
    java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    if (ancestor instanceof MainDashboard) {
        MainDashboard dashboard = (MainDashboard) ancestor;
        dashboard.showPanel("cardStaffMenu"); 
    }

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookingActionPerformed
   
    String roomNo = txtRoomNo.getText().trim();
    
    if (roomNo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a booked room from the table first!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to cancel the pending booking for Room " + roomNo + "?", 
            "Confirm Cancellation", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return; 
    }

    String updateRoomSql = "UPDATE rooms SET status = 'Available' WHERE room_no = ?";
    String deleteBookingSql = "DELETE FROM bookings WHERE room_no = ? AND DATE(check_in_date) >= CURDATE()"; 

    try (java.sql.Connection conn = DB_Connection.connect()) {
        conn.setAutoCommit(false); 

        try (java.sql.PreparedStatement pst1 = conn.prepareStatement(updateRoomSql);
             java.sql.PreparedStatement pst2 = conn.prepareStatement(deleteBookingSql)) {
            
            pst1.setString(1, roomNo);
            pst1.executeUpdate();

            pst2.setString(1, roomNo);
            pst2.executeUpdate();

            conn.commit(); 
            
            javax.swing.JOptionPane.showMessageDialog(this, "Room " + roomNo + " has been successfully released!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
         
            loadRoomData(); 
            clearFields();  
            
        } catch (Exception ex) {
            conn.rollback(); 
            throw ex;
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnCancelBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelBooking;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAmenities;
    private javax.swing.JComboBox<String> cmbRoomType;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNo;
    // End of variables declaration//GEN-END:variables
}
