/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel_Reservation_System;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
public class PanelGuests extends javax.swing.JPanel {

    /**
     * Creates new form PanelGuests
     */
    public PanelGuests() {
        initComponents();
        tblGuests.getParent().getParent().setVisible(false);
    }
    
    private void searchCustomer(String nic) {
        DefaultTableModel model = (DefaultTableModel) tblGuests.getModel();
        model.setRowCount(0); 
        
        
        model.setColumnIdentifiers(new String[]{"Guest ID", "Full Name", "NIC/Passport", "Contact Number"});

        String sql = "SELECT * FROM guests WHERE nic_or_passport = ?";
        
        try (Connection conn = DB_Connection.connect();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            
            pst.setString(1, nic);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
               int rawId = rs.getInt("guest_id");
               String formattedGuestId = String.format("G%03d", rawId);
                model.addRow(new Object[]{
                    formattedGuestId,
                  rs.getString("full_name"),
                    rs.getString("nic_or_passport"),
                    rs.getString("contact_number")
                });
                
                
                txtName.setText(rs.getString("full_name"));
                txtContact.setText(rs.getString("contact_number"));
                
                tblGuests.getParent().getParent().setVisible(true);
                this.revalidate();
                this.repaint();
                
            } else {
                JOptionPane.showMessageDialog(this, "Customer not found for this NIC!", "Not Found", JOptionPane.INFORMATION_MESSAGE);
                 tblGuests.getParent().getParent().setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGuests = new javax.swing.JTable();
        txtName1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Full Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 105, 105, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Customer Registration");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 21, 259, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NIC Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 206, 105, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 264, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 105, 749, -1));
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 203, 295, -1));
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 264, 210, -1));

        btnRegister.setBackground(new java.awt.Color(102, 153, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setText("Register Customer");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 160, 30));

        btnUpdate.setBackground(new java.awt.Color(102, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update Customer");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 30));

        btnDelete.setBackground(new java.awt.Color(102, 153, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete Customer");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 130, 30));

        btnClear.setBackground(new java.awt.Color(102, 153, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear Fields");
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 443, 110, 30));

        btnSearch.setBackground(new java.awt.Color(102, 153, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search Customer");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        tblGuests.setBackground(new java.awt.Color(204, 255, 204));
        tblGuests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "NIC Number", "Contact Number"
            }
        ));
        jScrollPane2.setViewportView(tblGuests);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 764, 110));

        txtName1.addActionListener(this::txtName1ActionPerformed);
        add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 145, 749, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
                                                
        if (txtName.getText().isEmpty() || txtNIC.getText().isEmpty() || txtContact.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO guests (full_name, nic_or_passport, contact_number) VALUES (?, ?, ?)";
        try (Connection conn = DB_Connection.connect();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, txtName.getText());
            pst.setString(2, txtNIC.getText());
            pst.setString(3, txtContact.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Customer Registered Successfully!");
            
            String currentNIC = txtNIC.getText();
            
            searchCustomer(currentNIC); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                                              
        if (txtNIC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the NIC to update!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE guests SET full_name = ?, contact_number = ? WHERE nic_or_passport = ?";
        try (Connection conn = DB_Connection.connect();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, txtName.getText());
            pst.setString(2, txtContact.getText());
            pst.setString(3, txtNIC.getText());
            
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Customer Updated Successfully!");
                searchCustomer(txtNIC.getText()); 
            } else {
                JOptionPane.showMessageDialog(this, "Customer NIC not found!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                                                
        if (txtNIC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the NIC to delete!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this customer?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM guests WHERE nic_or_passport = ?";
            try (Connection conn = DB_Connection.connect();
                 PreparedStatement pst = conn.prepareStatement(sql)) {

                pst.setString(1, txtNIC.getText());
                int rows = pst.executeUpdate();
                
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Customer Deleted Successfully!");
                    btnClearActionPerformed(null); 
                    DefaultTableModel model = (DefaultTableModel) tblGuests.getModel();
                    model.setRowCount(0); 
                } else {
                    JOptionPane.showMessageDialog(this, "Customer NIC not found!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cannot delete! Customer might have bookings.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText("");
        txtNIC.setText("");
        txtContact.setText("");
        DefaultTableModel model = (DefaultTableModel) tblGuests.getModel();
        model.setRowCount(0);
        
        tblGuests.getParent().getParent().setVisible(false);
        
        this.revalidate();
        this.repaint();
    
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                                          
        String nic = txtNIC.getText().trim();
        if (nic.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a NIC number to search!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        searchCustomer(nic);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblGuests;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    // End of variables declaration//GEN-END:variables
}
